/*
 * piecetype is a enum that contains the type of the piece
 * it has a method to get the opposite type
 */
public enum piecestatus {
    WHITE,BLACK,EMPTY,VALID;

    public piecestatus opp(){  //generated by llm
        return switch(this) {
            case WHITE -> BLACK;
            case BLACK -> WHITE;
            case EMPTY, VALID -> EMPTY;
        };
    }
}